name: Update Github Pages

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

  workflow_dispatch:

jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install missing software
      run: sudo apt update; sudo apt install doxygen graphviz
    - name: Build docs
      run: doxygen
    - name: Update documentation
      run: |
          git checkout docs
          rm -rf doxygen
          mv doxygen-new doxygen
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git config pull.rebase true
          git pull
          git commit -m "Обновление документации" && git push || true
  Lcov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install missing software
      run: sudo apt update; sudo apt install lcov
    - name: Make coverage
      run: make cov
    - name: Setup credentials
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
    - name: Update README
      run: |
          if [[ -n $(git status README.md --porcelain) ]]; then git add README.md; git commit -m "Обновление статуса покрытия в README"; git push; fi
    - name: Update coverage
      run: |
          git checkout docs
          rm -rf coverage
          mv coverage-new coverage
          git add .
          git commit -m "Обновление анализа покрытия кода"
          git config pull.rebase true
          git pull
          git push