name: Run tests

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, test, optimize ]
  pull_request:
    branches: [ master, test, optimize ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run
      run: ./test/test ./test/A-unit/unit*.ml ./test/B-unit/unit*.ml
