name: Test Compilation

on:
  push:
    branches: [ stable, dev ]
  pull_request:
    branches: [ stable, dev ]

  workflow_dispatch:

jobs:
  A-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run A-units
      run: ./fltest ./test/A-unit/unit*.ml
  B-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run B-units
      run: ./fltest ./test/B-unit/unit*.ml
  Valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: sudo apt install valgrind
    - name: Build
      run: make
    - name: Run Checks
      run: ./fltest -m ./test/A-unit/unit*.ml ./test/B-unit/unit*.ml