name: Test Compilation

on:
  push:
    branches: [ master, optimize ]
  pull_request:
    branches: [ master, optimize ]

  workflow_dispatch:

jobs:
  A-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run A-units
      run: ./mlc-test ./test/A-unit/unit*.ml
  B-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run B-units
      run: ./mlc-test ./test/B-unit/unit*.ml
  Valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: sudo apt install valgrind
    - name: Build
      run: make
    - name: Run Checks
      run: ./mlc-test -m ./test/A-unit/unit*.ml ./test/B-unit/unit*.ml