name: Test Optimization

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable, salvia ]

  workflow_dispatch:

jobs:
  A-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run A-units
      run: ./fltest -O ./test/A-unit/*.fl
  B-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run B-units
      run: ./fltest -O ./test/B-unit/*.fl
  Valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: sudo apt install valgrind
    - name: Build
      run: make
    - name: Run Checks
      run: ./fltest -O -m ./test/A-unit/*.fl ./test/B-unit/*.fl
